import { useState } from "react";
import { motion } from "framer-motion";
import { FileText, Download, Share2, Printer, CheckCircle } from "lucide-react";
import { GlassCard } from "@/components/ui/GlassCard";
import { AnimatedButton } from "@/components/ui/AnimatedButton";
import { StripType, BiomarkerResult } from "@/data/stripTypes";
import { getStatusColor, getStatusText } from "@/lib/analysisUtils";

interface ReportsTabProps {
  stripType: StripType;
  biomarkerResults: BiomarkerResult[];
  overallStatus: "normal" | "attention" | "critical";
  timestamp: Date;
  imageUrl: string | null;
}

export const ReportsTab = ({
  stripType,
  biomarkerResults,
  overallStatus,
  timestamp,
  imageUrl,
}: ReportsTabProps) => {
  const [generating, setGenerating] = useState(false);
  const [generated, setGenerated] = useState(false);

  const handleGenerateReport = async () => {
    setGenerating(true);
    // Simulate report generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    setGenerating(false);
    setGenerated(true);
  };

  const handleDownload = () => {
    // Create a simple text report (in production, this would generate a proper PDF)
    const reportContent = `
STRIPZ DIAGNOSTIC REPORT
========================

Analysis Date: ${timestamp.toLocaleDateString()} ${timestamp.toLocaleTimeString()}
Strip Type: ${stripType.name}
Overall Status: ${getStatusText(overallStatus)}

BIOMARKER RESULTS
-----------------
${biomarkerResults.map(r => `${r.name}: ${r.value} (${r.confidence}% confidence)`).join('\n')}

SUMMARY
-------
Total Biomarkers Analyzed: ${biomarkerResults.length}
Normal: ${biomarkerResults.filter(r => r.status === 'normal').length}
Attention: ${biomarkerResults.filter(r => r.status === 'attention').length}
Critical: ${biomarkerResults.filter(r => r.status === 'critical').length}

This report was generated by StripZ - Multi-Parameter Diagnostic Strip Intelligence Platform.
For professional medical advice, please consult with a healthcare provider.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `stripz-report-${stripType.id}-${timestamp.toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-xl font-semibold text-foreground">Reports</h2>
          <p className="text-muted-foreground">Generate and download professional analysis reports</p>
        </div>
      </div>

      {/* Report Preview */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
      >
        <GlassCard className="relative overflow-hidden">
          {/* Paper effect */}
          <div className="absolute inset-0 bg-gradient-to-br from-background to-muted/20" />
          
          <div className="relative">
            {/* Report Header */}
            <div className="flex items-start justify-between pb-6 border-b border-border/50">
              <div>
                <h3 className="text-2xl font-bold text-foreground mb-1">
                  Diagnostic Analysis Report
                </h3>
                <p className="text-muted-foreground">StripZ Intelligence Platform</p>
              </div>
              <div className="text-right">
                <div className="text-sm text-muted-foreground">Report ID</div>
                <div className="font-mono text-foreground">
                  STZ-{Math.random().toString(36).substr(2, 8).toUpperCase()}
                </div>
              </div>
            </div>

            {/* Report Details */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6 py-6">
              <div>
                <h4 className="text-sm font-medium text-muted-foreground mb-2">Analysis Details</h4>
                <div className="space-y-2">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Date</span>
                    <span className="text-foreground">{timestamp.toLocaleDateString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Time</span>
                    <span className="text-foreground">{timestamp.toLocaleTimeString()}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Strip Type</span>
                    <span className="text-foreground">{stripType.name}</span>
                  </div>
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Biomarkers</span>
                    <span className="text-foreground">{biomarkerResults.length}</span>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="text-sm font-medium text-muted-foreground mb-2">Overall Status</h4>
                <div
                  className="p-4 rounded-xl"
                  style={{ backgroundColor: getStatusColor(overallStatus) + "20" }}
                >
                  <div
                    className="text-xl font-bold mb-1"
                    style={{ color: getStatusColor(overallStatus) }}
                  >
                    {getStatusText(overallStatus)}
                  </div>
                  <p className="text-sm text-muted-foreground">
                    {overallStatus === "normal" && "All biomarkers within normal ranges"}
                    {overallStatus === "attention" && "Some biomarkers require monitoring"}
                    {overallStatus === "critical" && "Immediate attention recommended"}
                  </p>
                </div>
              </div>
            </div>

            {/* Biomarker Table */}
            <div className="py-6 border-t border-border/50">
              <h4 className="text-sm font-medium text-muted-foreground mb-4">Biomarker Results</h4>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-border/50">
                      <th className="text-left py-2 text-muted-foreground font-medium">Biomarker</th>
                      <th className="text-left py-2 text-muted-foreground font-medium">Status</th>
                      <th className="text-left py-2 text-muted-foreground font-medium">Value</th>
                      <th className="text-right py-2 text-muted-foreground font-medium">Confidence</th>
                    </tr>
                  </thead>
                  <tbody>
                    {biomarkerResults.map((result) => (
                      <tr key={result.name} className="border-b border-border/30">
                        <td className="py-2 text-foreground">{result.name}</td>
                        <td className="py-2">
                          <span
                            className="px-2 py-0.5 rounded text-xs font-medium"
                            style={{
                              backgroundColor: getStatusColor(result.status) + "20",
                              color: getStatusColor(result.status),
                            }}
                          >
                            {result.status}
                          </span>
                        </td>
                        <td className="py-2 text-foreground">{result.value}</td>
                        <td className="py-2 text-right text-foreground">{result.confidence}%</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Footer */}
            <div className="pt-6 border-t border-border/50 text-center">
              <p className="text-xs text-muted-foreground">
                This report was generated by StripZ - Multi-Parameter Diagnostic Strip Intelligence Platform.
                For professional medical advice, please consult with a healthcare provider.
              </p>
            </div>
          </div>
        </GlassCard>
      </motion.div>

      {/* Actions */}
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.2 }}
      >
        <GlassCard>
          <h3 className="font-semibold text-foreground mb-4">Export Options</h3>
          <div className="flex flex-wrap gap-4">
            {!generated ? (
              <AnimatedButton
                onClick={handleGenerateReport}
                disabled={generating}
                className="flex items-center gap-2"
              >
                {generating ? (
                  <>
                    <motion.div
                      animate={{ rotate: 360 }}
                      transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                    >
                      <FileText className="w-4 h-4" />
                    </motion.div>
                    Generating...
                  </>
                ) : (
                  <>
                    <FileText className="w-4 h-4" />
                    Generate Report
                  </>
                )}
              </AnimatedButton>
            ) : (
              <AnimatedButton
                variant="primary"
                onClick={handleDownload}
                className="flex items-center gap-2"
              >
                <Download className="w-4 h-4" />
                Download Report
              </AnimatedButton>
            )}

            <AnimatedButton variant="outline" className="flex items-center gap-2">
              <Share2 className="w-4 h-4" />
              Share
            </AnimatedButton>

            <AnimatedButton variant="ghost" className="flex items-center gap-2">
              <Printer className="w-4 h-4" />
              Print
            </AnimatedButton>
          </div>

          {generated && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="flex items-center gap-2 mt-4 text-success"
            >
              <CheckCircle className="w-4 h-4" />
              <span className="text-sm">Report ready for download</span>
            </motion.div>
          )}
        </GlassCard>
      </motion.div>
    </div>
  );
};
